version: "2"
services:
    reverseproxy:
        image: nginx
        container_name: ${NGINX_HOST}
        volumes:
            - ./etc/nginx/conf.d:/etc/nginx/conf.d
            - ./etc/ssl:/etc/ssl
            - ./www:/var/www/html
            - ./etc/nginx/conf.d/default.template:/etc/nginx/conf.d/default.template
            - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./etc/nginx/log/error.log:/var/log/nginx/error.log
        ports:
            - 80:80
            - 443:443
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/bash -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - web
    web:
        build: .
        container_name: ${APACHE_HOST}
        env_file:
            - ./.env
        entrypoint: [sh, /docker-entrypoint.sh]
        volumes:
            - ./www:/htdocs
            - ./README.md:/README.md
        ports:
            - 8069:80
        restart: always
        depends_on:
            - postgres
    postgres:
        image: postgres
        container_name: ${DB_HOST}
        env_file:
            - ./.env
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
            - POSTGRES_DB=${DB_NAME}
        volumes:
            - ./etc/postgres:/data/postgres
            - ./etc/postgres/init/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
        ports:
            - 5432:${DB_PORT}
        healthcheck:
            test:
                [
                    'CMD',
                    'pg_isready',
                    '-q',
                    '-d',
                    '${DB_NAME}',
                    '-U',
                    '${DB_USER}',
                ]
            retries: 3
            timeout: 5s
        restart: always
    pgadmin:
      image: dpage/pgadmin4
      container_name: ${PGADMIN_HOST}
      environment:
        PGADMIN_DEFAULT_EMAIL: ${SERVER_ADMIN}
        PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
        PGADMIN_LISTEN_PORT: ${PGADMIN_LISTEN_PORT}
      ports:
        - ${PGADMIN_LISTEN_PORT}:${PGADMIN_LISTEN_PORT}
      restart: always
      depends_on:
        - postgres